# Generated by Django 4.2 on 2023-04-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_test', '0003_alter_patientmedicalimage_patient_patientraysimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicalimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patientraysimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
