# Generated by Django 4.2 on 2023-06-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_test', '0004_patientmedicalimage_created_patientraysimage_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaltest',
            options={'ordering': ('-created',), 'verbose_name': 'Medical Test', 'verbose_name_plural': 'Medical Test'},
        ),
        migrations.AlterModelOptions(
            name='patientmedicalimage',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='patientraysimage',
            options={'ordering': ('-created',)},
        ),
    ]
