# Generated by Django 4.2 on 2023-06-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_test', '0005_alter_medicaltest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicalimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='patientraysimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
