# Generated by Django 4.2 on 2023-06-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_test', '0007_addmultiimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmultiimage',
            name='patient',
        ),
    ]
