# Generated by Django 4.2 on 2023-06-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_test', '0008_remove_addmultiimage_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddMultiImage',
        ),
    ]
