# Generated by Django 4.2 on 2023-06-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_test', '0015_remove_image_image_image_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
