# Generated by Django 4.2 on 2023-06-22 09:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_test', '0016_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientraysimage',
            old_name='image_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='patientraysimage',
            name='image',
        ),
        migrations.AddField(
            model_name='patientraysimage',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='patientraysimage',
            name='name',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
