# Generated by Django 4.2 on 2023-06-29 18:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_test', '0018_rename_image_url_patientmedicalimage_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalimage',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20000), blank=True, null=True, size=None),
        ),
    ]
