# Generated by Django 4.2 on 2023-06-29 19:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_test', '0021_alter_patientmedicalimage_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientraysimage',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, max_length=222222, null=True, size=None),
        ),
    ]
