# Generated by Django 4.2 on 2023-06-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_test', '0023_alter_patientraysimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientraysimage',
            name='images',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
