# Generated by Django 4.2 on 2023-06-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_test', '0025_alter_patientraysimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientraysimage',
            name='url',
            field=models.URLField(blank=True, max_length=200000),
        ),
    ]
