# Generated by Django 4.2 on 2023-04-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nat_id',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
