# Generated by Django 4.2 on 2023-07-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_patientmonitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmonitor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
