# Generated by Django 4.2 on 2023-07-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_patientmonitor_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientmonitor',
            options={'ordering': ('created',)},
        ),
    ]
