# Generated by Django 4.2 on 2023-07-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_patientmonitor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientmonitor',
            options={'ordering': ('-id',)},
        ),
    ]
