# Generated by Django 4.2 on 2023-04-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notificationapp_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationapp',
            name='title',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
