# Generated by Django 4.2 on 2023-04-28 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_device_token'),
        ('notification', '0004_notificationapp_user_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationapp',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_notification', to='users.patient'),
        ),
    ]
