# Generated by Django 4.2 on 2023-04-30 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notificationapp_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationapp',
            options={'ordering': ['-created']},
        ),
    ]
