# Generated by Django 4.2 on 2023-06-25 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0006_alter_notificationapp_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationapp',
            name='user_receiver',
        ),
        migrations.AddField(
            model_name='notificationapp',
            name='user_receiver',
            field=models.ManyToManyField(blank=True, related_name='user_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
