# Generated by Django 4.2 on 2023-04-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
