# Generated by Django 4.2 on 2023-06-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_medicine_time_clock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['-created'], 'verbose_name': 'Medicine', 'verbose_name_plural': 'Medicine'},
        ),
    ]
